#!/bin/bash
#
# MM-KB app is licensed under the MIT License. (c) 2020 Salai Aung Myint Myat.
# The license's description is found in the LICENSE.txt file.
# Also, credits to Ko Naing Ye` Minn (naingyeminn@gmail.com).

clear
echo "MM-KB is a Myanmar Keyboards which is a smart input keyboard."
echo "In this package, it contains two types of Burmese Keyboard: Unicode and ZawGyi-One."
echo "Also, credits to Ko Naing Yè Minn (naingyeminn@gmail.com) dedicated to Myanmar Keyboard for Ubuntu."
echo "Official Github: https://github.com/naingyeminn/mm-kb"
echo
echo "This MM-KB software is packaged and licensed under the MIT License. (c) 2020 Salai Aung Myint Myat."
echo "Assuming the user agree the MIT license by installing this software."
exit 0
